### ISSUE TITLE
How to verify openshift domain on mailgun?

### ISSUE THREAD

**Issue by sytolk** [openshift-quickstart/mailgun-openshift-quickstart#1]
To send emails with mailgun app-user.rhcloud.com domain must be verified
https://help.mailgun.com/hc/en-us/articles/202052074-How-do-I-verify-my-domain-

**Comment by axefox** [comment]
Same issue, Did you found any solution ?

**Comment by sytolk** [comment]
No I don`t. You can upload mailgun sending mail code to openshift but its need to have different domain verified from mailgun like this:
https://github.com/sytolk/acra-mailer/blob/master/acra.php#L680

**Comment by axefox** [comment]
Yeah i knw that. but how can we verify the openshift domain? :(

**Comment by marekjelen** [comment]
You can not send from .rhcloud.com domain, for sending e-mail you need your own private domain.
